# Generated by Django 5.2.7 on 2025-10-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capicity',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('vecant', 'vecant'), ('occupied', 'occupied'), ('reserved', 'reserved')], default='vecant', max_length=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
