# Generated by Django 5.2.7 on 2025-10-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_table_capicity_table_description_table_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tablecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
