# Generated by Django 5.2.7 on 2025-11-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_bill_item_name_bill_menu_item_bill_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myApp.bill')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.menuitem')),
            ],
        ),
    ]
