# Generated by Django 5.2.7 on 2025-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_kot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kot',
            name='kot_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
